cloudflareApiToken: ENC[AES256_GCM,data:r7RXnRIRDcxfv+yJnxDqAQ4Dc5HphdTRSI1QxRX6uiGk2165f0sqSjvSgpbChFayw59LG5+j/wDQBTs860S+1U4WfudJSEv0nYiAQ37/eGM=,iv:OEVrzkOTcMmJYS/U6oM+qvcMKc9/2/UYA1RxOOjdnew=,tag:vZL0HnsU7Ar4tyjiovDiuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRUpqTWdoSmVudXArTjJm
            ajVzM1lJWWRwZFppNVJ4UnF6MWFvQ2ZrNnhNCnRtNXlVdHkvQURYM0pzdlNPem1G
            TjU5V3p1TXJqdENPR1lsTTlJVUFrVUEKLS0tIHNNVkFNay9JaFQ5enpJWVl0N2s5
            R09nNGtHUEFYbWlEbis3OXFEdHNUMEEK5D9IJ8RgaYKSqyxW9bWviWvsa1h5ilSl
            dn3qoCBvrBugdzGC+XMTV4g5+Gi6TcasOgEhRef+XnzqhV4+Q+py2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ggptvx4jjezvzgc7w4jusjw5mejpl7l8qy9yt33qgjj58tgqde8qzldw7e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHMzb0xsb1NmL0J5WDBH
            bWZSaE0yNFdTVVM4Z1UrVFJaOHJXamx1K0hnCkNKM1FzU2xCb1U1SzgxbkxZTVA4
            cDRTVWYvdlZtakFZa1dSMjJ6TmF4cmsKLS0tIDJzMWJpemdkLzA5UTIvYjl1TFRY
            ZDlFTVkzK1pSSmVacTk0ZnBuY2lZTTgKYQfTbo9WjRCGlEaV8PgVw58wFo0Buea2
            Q3calzIB7cIzwrni/VeBbVs+XMFmDQvYYAYPb3b0OltiK8f9VAIinw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4q6596lcvf8zx8hzgudaz8wqselvf0a0hms54k508cesx9huemse46u96
    lastmodified: "2026-07-19T18:44:38Z"
    mac: ENC[AES256_GCM,data:RQ8TNZowASM0RNs4EX+X3D2eysaT9+Rh1CnB3B+V07WjjTW3ODDbLYQJ50GDTWBQVi94WYB/cyagmW6/bJ0LhQO7bN2bdUZjAlkVMBcWE4bH9PfFpVqE390y8LQCRt1FsvJe50pqIJ1AjWDgGpD+yX/DBB9xt751LMThzVCLLw8=,iv:dCS7MezQw7fdG71qGqQHlNZoJ642edi1Ae8heOfMk7M=,tag:XUDBLBRlnm3ypb4WC5yFyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
