postgresPassword: ENC[AES256_GCM,data:/VOdv8AIp1CElnsjWzw3fHyG,iv:9Q7PcNf8Pj2G3ocDz4ge+kdaBRGQWpZjjsQvCQcpEOY=,tag:Ua23TVYICBXS6ZhZlq2BZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVU9ZYnc0cmdxckJkeWhj
            K3NqN0RyZHFKOC9EOFgrLy9OMDh4Uk45bmlzCnM4U2tWbUFjOHRMcklER0xnRDZv
            RWwyblN3RTA0TldhR212b2xGeWtNdkkKLS0tIFZ4eVhTRXhoTjBOcDFjOXNxODdC
            ZVdTTmx1ZlZBZGY4RjN4SmhyTjd2MWcKUguVZkaaluArbmdTe1YHNwT1/xxOWCCC
            5MQnl6ZvH6DoM5FkVrnZWEMef8qyJKdRiONf9l0lvHnW592k5ISp6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ggptvx4jjezvzgc7w4jusjw5mejpl7l8qy9yt33qgjj58tgqde8qzldw7e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQXNyZTAxRmVJOFhkakdD
            OFFDeUpwNUd5Uzl5VlpGbmNVWHBCMTBLd1dFCkFGTW55L215TXdJdWhoelUvRzRi
            NzlHQ2lORUlKeFhoaHpCSG9vazhDeGMKLS0tIDhxTG1Ic3ZKTGhHT1NJeFNrV2Nu
            ajhUMHRJUEhkdndRNStSRnNTVWFCd1kKsZl8Tdck0Yi06j7LorenRbd6xw68bpkc
            nK3qctcmLlZ+rNyT7WrM87JgvLjFZo3TaNyiEcHAyfNOsDw9PFRKFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4q6596lcvf8zx8hzgudaz8wqselvf0a0hms54k508cesx9huemse46u96
    lastmodified: "2026-07-19T13:42:35Z"
    mac: ENC[AES256_GCM,data:2icxZbfZmOY6a6m3R+coIUDTm3c60rp7BRo7oh+OPMVIcXUIO0FWIkoqxBELdNRqLvS6A8/7D9NsJlaBy17TxOGM+NfxXmPG+Z4/T1ZGM9lFA8xkFRJVrybScwpe3VdOdVgOvJz9MHKTr1BnBvBOH3gUESTXP6ws8ewdpRPwl8A=,iv:8WcqBNWscxPsN59BnLe73X51cz57BFwEqj7sH+Ov2Kw=,tag:F7zmfo+aaZNbYmSM5CGnWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
