"""Chunker (HLD D5, D9): pure string/dataclass logic, no I/O. NOT heading aware, despite its
history: it does not split a doc on `##`/subheadings into separate sections. `chunk_document`
treats the WHOLE doc text as exactly one section; the only thing it reads out of markdown headings
is the doc's single H1 (`# `), used for `doc_title` and as the entire `heading_path` (always one
level deep: `(doc_title,)`). A section over the ~300 estimated token threshold (words x 1.3) splits
at SENTENCE boundaries (not heading boundaries) into ~300 token children, sharing one `parent_id`;
a section under the threshold stays whole. Every doc in the corpus committed so far (corpus-0.1.1,
max ~113 estimated tokens) has exactly one H1 and is well under the threshold, so `chunk_document`
degrades gracefully to exactly one chunk per doc, with `parent_id == doc_id`, rather than forcing
an artificial split. The sentence
boundary splitting branch exists for a future, larger corpus_version and is exercised here only by
a synthetic fixture. Section aware splitting (cutting at `##` boundaries instead of one giant
section) and a `heading_path` that carries real subheading depth are the named v2 seam this module
deliberately defers, not a bug in v1.

`chunk_id` is content addressed over five independent inputs: `corpus_version`, `doc_id`,
`doc_version`, `chunker_version`, and `span` (the char range). Changing any one of them, holding
the rest fixed, changes the id. `doc_version` is the caller's responsibility to supply (the
manifest's per doc content hash, per the digest's open decision 8); this module never reads the
corpus or the manifest itself.

Every input doc is assumed (and, on this corpus, guaranteed) to carry exactly one H1 heading,
regardless of where it falls in the doc: some rendered docs place their H2 sections before the
H1 title line (see `doc-plan_page-plan-fiber-100`), so title extraction scans the whole text
rather than assuming the first line.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass

CHUNKER_VERSION = "hchunk-1"

# Config constants that define this chunker's behavior. Hashed by chunker_hash() so an
# index_build_id (D9) can detect a chunking config change even when CHUNKER_VERSION itself is
# unchanged (e.g. a threshold tuned without a new named algorithm version).
_WORDS_TO_TOKENS_RATIO = 1.3
_SPLIT_THRESHOLD_TOKENS = 300
_CHILD_TARGET_TOKENS = 300

_HASH_HEX_LEN = 16

_H1_RE = re.compile(r"^# (.+)$", re.MULTILINE)
_SENTENCE_BOUNDARY_RE = re.compile(r"(?<=[.!?])\s+")


def chunker_hash() -> str:
    """sha256 of the chunker's config constants, first 16 hex chars. Deterministic: same config,
    same hash, every call."""
    config = {
        "chunker_version": CHUNKER_VERSION,
        "words_to_tokens_ratio": _WORDS_TO_TOKENS_RATIO,
        "split_threshold_tokens": _SPLIT_THRESHOLD_TOKENS,
        "child_target_tokens": _CHILD_TARGET_TOKENS,
    }
    canonical = json.dumps(config, sort_keys=True, separators=(",", ":"))
    return _sha256_16(canonical)


@dataclass(frozen=True)
class ChunkRecord:
    """One chunk's full binding metadata (chunk_id ... corpus_version, per the plan's Global
    Constraints schema) plus the two fields the metadata schema doesn't carry but embedding needs:
    `text` (the chunk's own content, header excluded) and `doc_title` (needed by `embed_text` to
    render the contextual header)."""

    chunk_id: str
    parent_id: str
    doc_id: str
    doc_version: str
    doc_type: str
    heading_path: tuple[str, ...]
    char_span: tuple[int, int]
    token_count: int
    content_hash: str
    entity_ids: tuple[str, ...]
    chunker_version: str
    corpus_version: str
    doc_title: str
    text: str

    @property
    def embed_text(self) -> str:
        """The text actually sent to the embedder: the contextual header, then the chunk text.
        `text` itself never carries the header, so chunking again with a header format change
        does not also change `content_hash`."""
        header = contextual_header(self.doc_title, self.heading_path)
        return f"{header}\n{self.text}"


def contextual_header(doc_title: str, heading_path: Sequence[str]) -> str:
    """`{doc_title} > {heading_path joined by ' > '}`, deterministic, not generated by an LLM."""
    return f"{doc_title} > {' > '.join(heading_path)}"


def chunk_document(
    doc_id: str,
    doc_type: str,
    text: str,
    doc_version: str,
    corpus_version: str,
    placements: Sequence[Mapping[str, object]],
) -> tuple[ChunkRecord, ...]:
    """Chunk one rendered doc's text into one or more `ChunkRecord`s.

    `placements` is the sidecar's `placements` list unchanged (each entry at least `fact_ref` and
    `span: [start, end]`); a chunk's `entity_ids` is the entity part (before the `:`) of every
    fact_ref whose placement span overlaps the chunk's own `char_span`, sorted and deduplicated.

    Pure function: no filesystem access, no wall clock, no randomness. `doc_id` must carry exactly
    one H1 heading (`# `) somewhere in `text`; this holds for every doc in corpus-0.1.1 by
    construction (SP2's renderer emits exactly one title heading per doc).
    """
    doc_title = _extract_doc_title(text)
    heading_path = (doc_title,)
    section_span = (0, len(text))

    if _estimate_tokens(text) <= _SPLIT_THRESHOLD_TOKENS:
        spans = (section_span,)
    else:
        spans = _split_into_children(text, section_span)

    return tuple(
        _build_chunk_record(
            doc_id=doc_id,
            doc_type=doc_type,
            doc_version=doc_version,
            corpus_version=corpus_version,
            doc_title=doc_title,
            heading_path=heading_path,
            span=span,
            text=text[span[0] : span[1]],
            parent_id=doc_id,
            placements=placements,
        )
        for span in spans
    )


def _build_chunk_record(
    *,
    doc_id: str,
    doc_type: str,
    doc_version: str,
    corpus_version: str,
    doc_title: str,
    heading_path: tuple[str, ...],
    span: tuple[int, int],
    text: str,
    parent_id: str,
    placements: Sequence[Mapping[str, object]],
) -> ChunkRecord:
    return ChunkRecord(
        chunk_id=_compute_chunk_id(corpus_version, doc_id, doc_version, span),
        parent_id=parent_id,
        doc_id=doc_id,
        doc_version=doc_version,
        doc_type=doc_type,
        heading_path=heading_path,
        char_span=span,
        token_count=_estimate_tokens(text),
        content_hash=_sha256_16(text),
        entity_ids=_entity_ids_for_span(span, placements),
        chunker_version=CHUNKER_VERSION,
        corpus_version=corpus_version,
        doc_title=doc_title,
        text=text,
    )


def _compute_chunk_id(corpus_version: str, doc_id: str, doc_version: str, span: tuple[int, int]) -> str:
    # CHUNKER_VERSION is read as a module global at call time (not bound as a default argument),
    # so a test that monkeypatches it observes the change here, exactly like a real algorithm
    # version bump would.
    start, end = span
    joined = "|".join([corpus_version, doc_id, doc_version, CHUNKER_VERSION, str(start), str(end)])
    return _sha256_16(joined)


def _sha256_16(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:_HASH_HEX_LEN]


def _entity_ids_for_span(span: tuple[int, int], placements: Sequence[Mapping[str, object]]) -> tuple[str, ...]:
    chunk_start, chunk_end = span
    entities: set[str] = set()
    for placement in placements:
        placement_start, placement_end = placement["span"]
        if placement_start < chunk_end and chunk_start < placement_end:
            fact_ref = str(placement["fact_ref"])
            entities.add(fact_ref.split(":", 1)[0])
    return tuple(sorted(entities))


def _estimate_tokens(text: str) -> int:
    word_count = len(text.split())
    return round(word_count * _WORDS_TO_TOKENS_RATIO)


def _extract_doc_title(text: str) -> str:
    match = _H1_RE.search(text)
    if match is None:
        raise ValueError("chunk_document requires exactly one H1 heading ('# ...') in doc text")
    return match.group(1).strip()


def _split_into_children(text: str, section_span: tuple[int, int]) -> tuple[tuple[int, int], ...]:
    """Split an over threshold section into ~300 estimated token children at sentence boundaries.
    Greedy: accumulate whole sentences until the next one would push the running child over
    target, then cut right before it. Spans are contiguous and non overlapping by construction
    (every cut point is a position inside `text`, and the section's own [start, end) is fully
    covered), so concatenating the resulting spans' text always reconstructs the section text
    exactly."""
    section_start, section_end = section_span
    section_text = text[section_start:section_end]
    split_points = [m.end() for m in _SENTENCE_BOUNDARY_RE.finditer(section_text)]
    split_points.append(len(section_text))

    spans: list[tuple[int, int]] = []
    child_start = 0
    running_tokens = 0
    prev_point = 0
    for point in split_points:
        sentence_tokens = _estimate_tokens(section_text[prev_point:point])
        if running_tokens > 0 and running_tokens + sentence_tokens > _CHILD_TARGET_TOKENS:
            spans.append((section_start + child_start, section_start + prev_point))
            child_start = prev_point
            running_tokens = 0
        running_tokens += sentence_tokens
        prev_point = point
    # Guard against an empty trailing span: `split_points` always ends with an appended
    # `len(section_text)`, which duplicates the regex's own last match when the final real
    # sentence boundary already lands exactly at the section's end (trailing whitespace after the
    # final '.'/'!'/'?'). That duplicate is a zero-token "sentence" that can still trip the cut
    # condition above (off the running total carried over from the real final sentence), landing
    # `child_start` exactly on `len(section_text)` -- unguarded, the unconditional append below
    # would then emit a `(len(section_text), len(section_text))` empty span. Never fires on any
    # committed or existing synthetic fixture text; reachable only with a crafted input (see
    # `test_split_into_children_never_appends_an_empty_trailing_span` in test_chunker.py).
    if child_start < len(section_text):
        spans.append((section_start + child_start, section_start + len(section_text)))
    return tuple(spans)
