apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.images.alertmanager.repository }}@{{ .Values.images.alertmanager.digest }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - name: http
              containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
              readOnly: true
            - name: data
              mountPath: /alertmanager
      volumes:
        - name: config
          secret:
            secretName: alertmanager-config
        - name: data
          emptyDir: {}
