"""SP6 task 2: the pure attribute translation table between `atlas_graph.py`'s informal span
vocabulary (`ok`, `model`, `degradation_mode`, `tool`, `args`, `result`, ...) and the frozen trace
contract's dotted names (`atlas.guard.decision`, `gen_ai.request.model`, `atlas.degradation.mode`,
...). No framework import (no langgraph/mcp/fastapi/opentelemetry/httpx/psycopg): a plain function
over `(name, kind, attrs)`, the exact shape `atlas_graph.py` already passes to `tracer.open(...)`,
mirroring `contract_tools`'s own pure, tested style. `otel_tracer.py` is this module's only caller;
`atlas_graph.py`'s ~20 `tracer.open()` call sites stay completely untouched.

Fails closed, in the adapter's export path, on two independent things:

1. An UNINVENTORIED span: `(name, kind, sorted(attrs.keys()))` was never observed by the committed
   golden inventory (`contracts/trace/span_inventory.json`, regenerated by
   `contract_tools.trace_inventory`, the same "regenerate and assert equality" mechanism
   `contract_tools.mcp_snapshot` already established for MCP tool schemas). A NEW, unreviewed call
   site (a renamed span, an added kwarg) can never silently reach an exported trace with the wrong
   vocabulary; the committed inventory must be regenerated and the diff reviewed first.

   `kind="tool"` spans are the one deliberate exception: the inventory records them under a
   WILDCARD name (`contract_tools.trace_inventory.TOOL_WILDCARD`), never the real, dynamic tool
   name (`get_account_summary`, `search_knowledge`, `change_plan`, ...). Which tools exist is
   `atlas.domain.binding`'s own concern, not a translation one -- every tool span carries exactly
   one of two attribute shapes (`args`+`result` for a read/catalog/knowledge call, `args`+`proposal`
   for a write) and the translation below treats both identically regardless of which tool produced
   them, so per tool name inventory entries would only add churn, never catch a real translation gap.

2. An UNMAPPED attribute key: even on an inventoried span, a key with no entry in `_KEY_RULES`/
   `_PASSTHROUGH_KEYS` below raises rather than silently dropping (or worse, silently forwarding
   under its raw name when a reviewer never actually decided that was fine).

Design decisions this table encodes, all resolved from the OBSERVED call sites in
`atlas_graph.py` (SP6 planning digest section 3, design question 1), never guessed:

- `kind="guard"` + `ok` -> `atlas.guard.decision`, `True`/`False` -> `"allow"`/`"block"`. No guard
  span anywhere in the codebase ever carries a third, step up signal (every one of the ~10 guard
  call sites passes only a bool `ok`); `"step_up"` is therefore never emitted by this table. If a
  future guard grows a real step up signal, add its key here explicitly -- never infer one from
  `ok` alone.
- `degradation_mode` (on the `agent`/`llm` fallback span and the `refusal`/`node` span) ->
  `atlas.degradation.mode` directly: the values already match the contract's 6 member enum
  (`atlas.domain.degradation.escalate`'s own return values), so this is a rename, not a transform.
- `kind="llm"` + `model` -> `gen_ai.request.model` (OTel GenAI semconv naming, D13's "extend, don't
  fork").
- Every other observed key (`reason`, `tool`, `tools`, `intent`, `input`, `hit`, `generic`, `args`,
  `result`, `proposal`, `applied`, `reference`, `output`, `retryable`) has no reserved contract
  counterpart (`testing/harness/contract_tools/loader.py::RESERVED_TRACE_ATTRIBUTES`); the trace
  schema's `attributes` object allows arbitrary additional properties, so these pass through
  UNCHANGED as informal, un namespaced diagnostic attributes -- a deliberate decision, not an
  oversight, so a reviewer can see every key was actually considered.

Two carries this module's docstring is the disclosed home for (SP4 Task 4 / Task 6 ledger lines,
per the SP6 plan and digest):

- `needs_refusal`: `AtlasState`'s own per turn routing signal (`atlas_graph.py`'s `AtlasState`
  TypedDict) is checked against every observed span in the committed inventory -- it never appears
  as a `tracer.open(...)` keyword argument anywhere. It is internal routing state only, never a
  span attribute, and this is the recorded answer to that carry, not an oversight.
- step up (`atlas.guard.decision`'s third enum member): see the guard bullet above. No observed
  guard span carries a step up signal, so it is never emitted; this is resolved from the observed
  inventory, not guessed, per the plan's own instruction.

Stage durations (`atlas.stage.embed_ms`/`retrieve_ms`/`rerank_ms`/`assemble_ms`/`ttft_ms`) are a
SEPARATE, name keyed mechanism (`STAGE_DURATION_ATTRIBUTE` below), computed by `otel_tracer.py`'s
`close(seq)` from its own injected monotonic clock, never derived from this module's inventory
based key table (a `kind="stage"` span carries no informal attributes at open time -- there is
nothing to translate until `close()` supplies a duration).

`atlas.stage.ttft_ms`'s own definition (SP6 task 2 fix round 1, landed after review's Important 1):
wall clock from `chat_app._run_stream`'s own turn start (this generator's first executed line,
before the graph has produced a single event) to the first content bearing SSE event that function
actually yields to the client -- NOT strict OTel GenAI "model first token." This graph fully
buffers its guarded answer and only then streams word chunks (`chat_app.py`'s own `_run_stream`
docstring), so a raw model level first token is never observable from this edge; "turn start to
first streamed content reaching the client" is the most honest boundary available here, and is the
definition any alerting built on this attribute (T5) must treat as authoritative.

Circuit breaker operational state (`CircuitBreaker.state()`) is deliberately ABSENT from every span
attribute in this table. It is live gauge data (the current open/closed/half open state of a
shared resource), not a per turn fact worth attaching to one turn's trace, so it belongs on the
metrics surface, not here: it lands as a Prometheus gauge, deferred to Task 5, and intentionally
has no `RESERVED_TRACE_ATTRIBUTES` slot.

SP6 task 7 (the v1 freeze): the emitter checklist against all 29 `RESERVED_TRACE_ATTRIBUTES` found
10 already emitted (above) and 10 with no real producer anywhere in this codebase, narrowed out of
the freeze via `ADR-029` (machine readable companion:
`contracts/trace/freeze_narrowed.yaml`, `testing/harness/contract_tools/freeze_check.py` reads it as
the single authority). The remaining nine are build wide constants this module already has every
fact it needs to compute -- `BUILD_ATTRIBUTES` below, stamped on every span (not turn only, unlike
`atlas.config.hash`/`atlas.corpus.version`/`atlas.index.build_id`, which stay in `otel_tracer.py`
because they come from `AtlasSettings`, not from anything this module owns).
"""
from __future__ import annotations

import hashlib
import hmac
import json
from pathlib import Path
from typing import Any, Mapping

# Anchored on this file (not the CWD), the same pattern `AtlasSettings`/`PgvectorRetriever` already
# use, so this module works regardless of where the process was started from.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_INVENTORY_PATH = _REPO_ROOT / "contracts" / "trace" / "span_inventory.json"

# The wildcard name every `kind="tool"` span is inventoried and checked under, regardless of its
# real (dynamic) tool name -- see the module docstring's point 1. Duplicated as a literal (not
# imported from `contract_tools.trace_inventory`, which is harness code backend must never import,
# `testing/tests/test_import_lint.py`'s own boundary) and cross checked by a hermetic test instead.
TOOL_WILDCARD = "*"


# ---- SP8 task 1: the subject pseudonym (D27) -----------------------------------------------------
#
# atlas.subject.pseudonym: an HMAC-SHA256 of customer_id, truncated to the same 16 hex character
# length `_redaction_policy_version`/`index_build_id`/`config_hash` already use elsewhere in this
# repo. Stable per customer (the SAME customer_id always yields the SAME pseudonym) -- the whole
# point of D27's "right to erasure reduces to pseudonym keyed deletes": a real deployment could find
# every trace for one customer by pseudonym without the exported trace ever carrying the raw id.
# Never reversible to customer_id without the key (unlike a plain digest, which anyone who guesses or
# enumerates candidate customer_ids could confirm by re-hashing).
#
# `_PSEUDONYM_KEY` mirrors `backend/atlas/auth.py`'s own `_KEY`: a fixed, local, first party key
# (this reference system's whole corpus is fabricated demo data, CLAUDE.md's own "known, intentional
# simplifications"), never a real secret manager -- the same posture `auth.py`'s own comment already
# documents for its signing key ("not a production secret").
_PSEUDONYM_KEY = b"atlas-local-dev-pseudonym-key-not-a-production-secret-v1"
_PSEUDONYM_HEX_LEN = 16


def pseudonym_for(customer_id: str) -> str:
    """HMAC-SHA256 of `customer_id`, truncated to `_PSEUDONYM_HEX_LEN` hex characters. The ONE
    computation `atlas.subject.pseudonym` values ever come from, live or hermetic -- see the module
    level comment above for why this is HMAC, not a plain digest. `str(customer_id)` (never a bare
    `.encode`): `freeze_check.hermetic_emitted_attributes`/`redaction.emitted_gen_ai_attributes` walk
    the committed span inventory with a placeholder `True` standing in for every real value (they
    only care which ATTRIBUTE NAMES a shape translates to, never the values), so this must tolerate
    a non string placeholder exactly like every other rule in this table already does."""
    mac = hmac.new(_PSEUDONYM_KEY, str(customer_id).encode("utf-8"), hashlib.sha256)
    return mac.hexdigest()[:_PSEUDONYM_HEX_LEN]


class TraceTranslationError(RuntimeError):
    """Base class for a fail closed translation refusal (SP6 task 2)."""


class UninventoriedSpanError(TraceTranslationError):
    """A `(name, kind, attrs)` shape the committed golden inventory never observed."""


class UnmappedAttributeError(TraceTranslationError):
    """An inventoried span carries a key with no translation rule below."""


def _load_inventory() -> frozenset[tuple[str, str, frozenset[str]]]:
    if not _INVENTORY_PATH.is_file():
        # Fail closed before ANY translation happens, the same "fail before the network call"
        # discipline `PgvectorRetriever._load_fingerprint` uses: a missing inventory is a build
        # problem, never a silent "nothing is inventoried" pass through.
        raise TraceTranslationError(
            f"no committed span inventory at {_INVENTORY_PATH}; generate one with "
            "`uv run python -m contract_tools.trace_inventory --write` before this adapter can export."
        )
    raw = json.loads(_INVENTORY_PATH.read_text())
    return frozenset((entry["name"], entry["kind"], frozenset(entry["attrs"])) for entry in raw)


# Loaded once at import time: the inventory is a committed, reviewed file, not something that
# changes mid process. A test that wants a DIFFERENT inventory (proving the fail closed behavior
# itself) calls `translate_span` with an explicit `inventory=` override instead of touching this.
_INVENTORY = _load_inventory()

# ---- the key translation table -----------------------------------------------------------------

# key -> dotted contract name, verbatim value (no transform needed: the value already matches the
# contract's own enum/shape at the source, see the module docstring).
_DIRECT_RENAME: dict[str, str] = {
    "degradation_mode": "atlas.degradation.mode",
}

# Keys with no reserved contract counterpart: pass through unchanged (module docstring, point 2).
_PASSTHROUGH_KEYS: frozenset[str] = frozenset({
    "input", "intent", "hit", "generic", "reason", "tool", "tools",
    "args", "result", "proposal", "applied", "reference", "output", "retryable",
})


def _inventory_key(name: str, kind: str, attrs: Mapping[str, Any]) -> tuple[str, str, frozenset[str]]:
    checked_name = TOOL_WILDCARD if kind == "tool" else name
    return (checked_name, kind, frozenset(attrs.keys()))


def _translate_attr(kind: str, key: str, value: Any) -> tuple[str, Any]:
    if key == "ok" and kind == "guard":
        return "atlas.guard.decision", ("allow" if value else "block")
    if key == "model" and kind == "llm":
        return "gen_ai.request.model", value
    # SP8 task 1: the subject pseudonym. `customer_id` is threaded through atlas_graph.py's "turn"
    # tracer.open call site as a new kwarg (per ADR-029), sourced from the session/bearer identity,
    # never a tool argument and never the model (CLAUDE.md's own rule) -- this is the ONE place the
    # raw id is ever seen by this module, and it is HMAC'd (`pseudonym_for`, never passed through
    # verbatim) before it becomes an attribute value.
    if key == "customer_id" and kind == "turn":
        return "atlas.subject.pseudonym", pseudonym_for(value)
    # SP8 task 1: the judge's own span (`judge.emission.emit_verdict`'s informal kwarg names). A
    # straight rename, no value transform: `judge_id` is already the contract's fingerprint digest,
    # `rubric_version` is already the rubric's own version string, and `verdict` is already the WIRE
    # vocabulary (`judge.llm_judge.translate_verdict`'s own output) by the time it reaches here --
    # this table never translates the judge's PASS/FAIL prompt vocabulary itself.
    if kind == "judge" and key == "judge_id":
        return "atlas.judge.id", value
    if kind == "judge" and key == "rubric_version":
        return "atlas.judge.rubric_version", value
    if kind == "judge" and key == "verdict":
        return "atlas.judge.verdict", value
    # SP9 task 5: the usage accounting trio (ADR-029's cost amendment). `matrix/cost_emission.py`'s
    # own informal kwarg names, on the SAME kind="llm" span shape `agent`'s own `model` key already
    # uses -- scoped to kind=="llm" only (never a blanket rename), so the same key on a different
    # kind still fails closed rather than silently aliasing.
    if kind == "llm" and key == "input_tokens":
        return "atlas.cost.input_tokens", value
    if kind == "llm" and key == "output_tokens":
        return "atlas.cost.output_tokens", value
    if kind == "llm" and key == "usd":
        return "atlas.cost.usd", value
    if key in _DIRECT_RENAME:
        return _DIRECT_RENAME[key], value
    if key in _PASSTHROUGH_KEYS:
        return key, value
    raise UnmappedAttributeError(
        f"span (kind={kind!r}) attribute {key!r} has no translation rule in "
        "backend/atlas/adapters/trace_translation.py's key table; add one (a dotted rename or an "
        "explicit passthrough decision) before this can export."
    )


def translate_attributes(
    name: str, kind: str, attrs: Mapping[str, Any], *, inventory: frozenset | None = None,
) -> dict[str, Any]:
    """Translate one observed span's informal `attrs` into the frozen contract's dotted names.
    Fails closed (raises `UninventoriedSpanError`/`UnmappedAttributeError`) rather than silently
    dropping or silently forwarding anything not already reviewed. `inventory` is test only (the
    fail closed behavior itself needs a controllable inventory); production callers never pass it,
    so they always check against the one committed file loaded at import time."""
    allowed = _INVENTORY if inventory is None else inventory
    key = _inventory_key(name, kind, attrs)
    if key not in allowed:
        raise UninventoriedSpanError(
            f"span (name={name!r}, kind={kind!r}, attrs={sorted(attrs.keys())}) was never observed "
            "by the committed span inventory (contracts/trace/span_inventory.json). Regenerate it "
            "(`uv run python -m contract_tools.trace_inventory --write`) after reviewing this new "
            "call site's vocabulary, then commit the diff."
        )
    return dict(_translate_attr(kind, k, v) for k, v in attrs.items())


# `translate_attributes` is defined above the SP6 task 7 (v1 freeze) `BUILD_ATTRIBUTES` section
# below (moved up from its previous position, SP6 task 7 review fix round 1) so
# `_redaction_policy_version` can call it directly, deriving the SAME gen_ai.* emitter set
# `contract_tools.redaction.emitted_gen_ai_attributes` derives via an import of this module, without
# this backend module ever importing testing harness code back (`test_import_lint.py`'s own
# boundary; harness may import backend, never the reverse).

# The five reserved stage duration attributes, keyed by the span NAME `atlas_graph.py`/`chat_app.py`
# open (embed/retrieve/rerank/assemble in the read loop; ttft in chat_app at first token). Task
# defined, not inventory derived (module docstring's own note): `otel_tracer.py`'s `close(seq)`
# reads this directly rather than routing a stage span's (empty) attrs through `translate_span`.
STAGE_DURATION_ATTRIBUTE: dict[str, str] = {
    "embed": "atlas.stage.embed_ms",
    "retrieve": "atlas.stage.retrieve_ms",
    "rerank": "atlas.stage.rerank_ms",
    "assemble": "atlas.stage.assemble_ms",
    "ttft": "atlas.stage.ttft_ms",
}

# The two attributes `contracts/trace/schema.json` REQUIRES on every exported span's `attributes`
# object. Stamped on every span (not only "turn", unlike `atlas.config.hash` which stays turn only
# per Task 1): `atlas.privacy.synthetic` is always True in this reference system (every seed
# account/plan/ticket is fabricated demo data, never a real customer's), and
# `atlas.contract.trace_version` is read directly off the committed schema file (a plain JSON read,
# not a `contract_tools` import -- see the module docstring's import lint note) so the two can never
# drift apart by hand.
def _contract_trace_version() -> str:
    schema = json.loads((_REPO_ROOT / "contracts" / "trace" / "schema.json").read_text())
    return schema["x-contract-version"]


_CONTRACT_TRACE_VERSION = _contract_trace_version()

REQUIRED_SPAN_ATTRIBUTES: dict[str, Any] = {
    "atlas.contract.trace_version": _CONTRACT_TRACE_VERSION,
    "atlas.privacy.synthetic": True,
}


# ---- SP6 task 7 (the v1 freeze): build wide constants, stamped on EVERY span ---------------------
#
# Seven of the freeze's ten "cheaply emittable now" attributes (the freeze report's own table):
# process wide FACTS this module already has everything it needs to compute, never per turn data a
# call site would have to start threading through. Kept deliberately separate from
# REQUIRED_SPAN_ATTRIBUTES above (which mirrors `contracts/trace/schema.json`'s own `required` array
# byte for byte, pinned by `test_required_span_attributes_are_exactly_the_schemas_own_required_pair`
# -- these seven are NOT schema required, they are simply always true for THIS build, and the schema
# already allows arbitrary additional properties). Merged into `translate_span`'s output below and
# (`otel_tracer.py`) into every STAGE span too, so the constant is genuinely on every exported span,
# not only the ones that happen to flow through `translate_span`.
def _contract_family_version(family: str) -> str:
    """The SAME plain JSON read `_contract_trace_version` above already uses, generalized to the
    other three contract families: `atlas.contract.dataset_version`/`manifest_version`/`sse_version`
    name which schema version THIS build was compiled against, exactly the same fact
    `atlas.contract.trace_version` already names for the trace family itself. A plain file read
    (never a `contract_tools` import), so this module's purity claim
    (`test_trace_translation_module_stays_pure`) is unaffected."""
    schema = json.loads((_REPO_ROOT / "contracts" / family / "schema.json").read_text())
    return schema["x-contract-version"]


def _semconv_version() -> str:
    """`atlas.semconv.version`: the real OTel GenAI semantic conventions pin Task 1 recorded
    (pyproject.toml's own comment: "opentelemetry-api/sdk ... pinned at or above the transitively
    resolved 1.43.0/0.64b0"). Read from the INSTALLED package's own metadata
    (`opentelemetry-semantic-conventions`, a guaranteed present transitive dependency of
    `opentelemetry-sdk`, itself a direct, always installed `[project]` dependency -- never the
    optional `observability` group) rather than hand copied, so this can never silently drift from
    whatever the lockfile actually resolved. `importlib.metadata` is the standard library, not a
    framework import, so this module's purity claim holds."""
    from importlib.metadata import version

    return version("opentelemetry-semantic-conventions")


# `atlas.variant`: this repository IS one fixed point in the blog series' naive/agentic/graph
# comparison (README.md's own framing: "a LangGraph + MCP broadband support agent"), never a
# runtime choice -- there is no ATLAS_VARIANT env var and no code path that produces "naive" or
# "agentic" output from this codebase. A build wide constant, not a settings read.
_ATLAS_VARIANT = "graph"

# `atlas.privacy.content_captured`: whether an exported, REDACTED span still carries literal
# customer/turn content. `contract_tools.redaction.allowed_attributes()` (SP6 task 3) allowlists
# ONLY `RESERVED_TRACE_ATTRIBUTES` plus the `gen_ai.*` keys this table actually emits plus
# `openinference.span.kind` -- every informal, free text passthrough key this module's
# `_PASSTHROUGH_KEYS` produces (`input`, `output`, `args`, `result`, `reason`, ...) is stripped by
# the collector's redaction processor BEFORE either fan out target (Phoenix, the raw archive) ever
# sees it. False is therefore a build wide fact about what actually leaves the collector, not a
# per span judgment call: no reserved attribute is ever free text, so redacted, exported evidence
# never captures content, regardless of which span this lands on.
_CONTENT_CAPTURED = False

# `atlas.privacy.redaction_policy_version` (SP6 task 7 review fix round 1, Important 1 -- the
# versioning trap): this used to be a literal copy of `_CONTRACT_TRACE_VERSION`. That is a real gap,
# not just an identity: `contract_tools.redaction.allowed_attributes()` unions `RESERVED_TRACE_
# ATTRIBUTES` (tied to the trace schema) with the `gen_ai.*` keys THIS table actually emits (tied to
# nothing but this table itself, entirely independent of `contracts/trace/schema.json`) and
# `openinference.span.kind`. A future PR adding a new `gen_ai.*` mapping below changes the REAL
# redaction allowlist with no bump obligation attached to the trace schema at all, and the copied
# version string would never move to say so.
#
# The fix is CONTENT ADDRESSING, the same "hash the canonical content, truncate to a short hex
# prefix" philosophy `chunk_id`/`index_build_id`/`config_hash` already use elsewhere in this repo:
# a short sha256 prefix over the allowlist's own canonical, sorted key list. This module cannot
# import `contract_tools.redaction.redaction_policy_version` to get that value directly (a backend
# module may never import testing harness code, `test_import_lint.py`'s own boundary, and doing so
# would also be a genuine circular import: `contract_tools.redaction` itself imports THIS module to
# derive its own gen_ai.* category). Instead, the three helpers below independently recompute the
# SAME three allowlist inputs, entirely from committed files and this module's own translation
# table, and hash them the SAME way -- `testing/tests/test_trace_translation.py` cross checks the
# result against `contract_tools.redaction.redaction_policy_version()`'s own output, the same
# "two independent implementations over the same underlying data, cross checked by a test, never a
# Python import" discipline `_contract_family_version`/`contract_tools.loader.contract_versions()`
# already established for the other three contract family versions.
_POLICY_VERSION_HEX_LEN = 16
_OPENINFERENCE_SPAN_KIND_ATTRIBUTE = "openinference.span.kind"


def _reserved_trace_attributes_from_schema() -> tuple[str, ...]:
    """The trace schema's OWN declared attribute property names, read directly from the committed
    file (never a `contract_tools.loader.RESERVED_TRACE_ATTRIBUTES` import -- see the comment
    above). `testing/harness/contract_tools/loader.py`'s own 29 name literal is the SAME set, in the
    SAME order; `test_reserved_trace_attributes_from_schema_matches_the_loaders_own_list` cross
    checks the two stay in agreement rather than assuming it by construction."""
    schema = json.loads((_REPO_ROOT / "contracts" / "trace" / "schema.json").read_text())
    return tuple(schema["properties"]["attributes"]["properties"].keys())


def _emitted_gen_ai_attributes() -> frozenset[str]:
    """Every `gen_ai.*` key `translate_attributes` (above) actually produces when walking the
    committed golden span inventory -- the exact SAME derivation `contract_tools.redaction.
    emitted_gen_ai_attributes()` performs via an import of THIS module's `translate_attributes`,
    performed here as a local call instead so this module never has to import back out to the
    harness that already imports it."""
    entries = json.loads(_INVENTORY_PATH.read_text())
    keys: set[str] = set()
    for entry in entries:
        attrs = {key: True for key in entry["attrs"]}
        translated = translate_attributes(entry["name"], entry["kind"], attrs)
        keys.update(key for key in translated if key.startswith("gen_ai."))
    return frozenset(keys)


def _redaction_policy_version() -> str:
    """The SAME computation `contract_tools.redaction.redaction_policy_version()` performs over
    `allowed_attributes()`, independently recomputed here from this module's own three sources
    (never an import; see the block comment above): a short sha256 prefix over the canonical,
    sorted union of the reserved names, the emitted gen_ai.* keys, and the openinference span kind
    constant, newline joined -- identical inputs, identical algorithm, so the two values agree
    without ever sharing code."""
    allowed = sorted(
        set(_reserved_trace_attributes_from_schema())
        | _emitted_gen_ai_attributes()
        | {_OPENINFERENCE_SPAN_KIND_ATTRIBUTE}
    )
    canonical = "\n".join(allowed)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:_POLICY_VERSION_HEX_LEN]


BUILD_ATTRIBUTES: dict[str, Any] = {
    "atlas.semconv.version": _semconv_version(),
    "atlas.variant": _ATLAS_VARIANT,
    "atlas.contract.dataset_version": _contract_family_version("dataset"),
    "atlas.contract.manifest_version": _contract_family_version("manifest"),
    "atlas.contract.sse_version": _contract_family_version("sse"),
    "atlas.privacy.content_captured": _CONTENT_CAPTURED,
    "atlas.privacy.redaction_policy_version": _redaction_policy_version(),
}

# span_kind: the openinference style top level discriminator `contracts/trace/schema.json` requires
# (CHAIN/RETRIEVER/RERANKER/LLM/TOOL/GUARDRAIL/EVALUATOR) -- an entirely different axis from OTel's
# own native `SpanKind` (CLIENT/SERVER/INTERNAL/...), never confused with it here.
_KIND_TO_SPAN_KIND: dict[str, str] = {
    "turn": "CHAIN",
    "node": "CHAIN",
    "llm": "LLM",
    "tool": "TOOL",
    "guard": "GUARDRAIL",
    "judge": "EVALUATOR",  # SP8 task 1: the judge's own span (judge.emission.emit_verdict)
}
_STAGE_NAME_TO_SPAN_KIND: dict[str, str] = {
    "embed": "RETRIEVER",
    "retrieve": "RETRIEVER",
    "rerank": "RERANKER",
    "assemble": "CHAIN",
    "ttft": "CHAIN",
}


def span_kind_for(name: str, kind: str) -> str:
    """The contract's `span_kind` enum value for one observed `(name, kind)` pair."""
    if kind == "stage":
        return _STAGE_NAME_TO_SPAN_KIND.get(name, "CHAIN")
    return _KIND_TO_SPAN_KIND.get(kind, "CHAIN")


def translate_span(name: str, kind: str, attrs: Mapping[str, Any], *, inventory: frozenset | None = None) -> dict:
    """The full contract shaped span record (`{"name", "span_kind", "attributes"}`,
    `contracts/trace/schema.json`'s own top level shape) for one observed span: translated
    attributes (`translate_attributes`) merged with the two universally required ones
    (`REQUIRED_SPAN_ATTRIBUTES`). A caller supplied attribute never loses to a required one with the
    same key (there are none today; `REQUIRED_SPAN_ATTRIBUTES` intentionally never overlaps
    `_DIRECT_RENAME`/`_PASSTHROUGH_KEYS`'s own targets)."""
    translated = translate_attributes(name, kind, attrs, inventory=inventory)
    return {
        "name": name,
        "span_kind": span_kind_for(name, kind),
        "attributes": {**REQUIRED_SPAN_ATTRIBUTES, **BUILD_ATTRIBUTES, **translated},
    }


__all__ = [
    "BUILD_ATTRIBUTES",
    "REQUIRED_SPAN_ATTRIBUTES",
    "STAGE_DURATION_ATTRIBUTE",
    "TOOL_WILDCARD",
    "TraceTranslationError",
    "UnmappedAttributeError",
    "UninventoriedSpanError",
    "span_kind_for",
    "translate_attributes",
    "translate_span",
]
